[[redirects]]
  from = "/conciliapp"
  to = "https://conciliapps.netlify.app/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/conciliapp/*"
  to = "https://conciliapps.netlify.app/:splat"
  status = 200
  force = true
